// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server;

namespace server.Migrations
{
    [DbContext(typeof(TideTrackerContext))]
    [Migration("20181006020420_NarrowedDownDataToWorkingData")]
    partial class NarrowedDownDataToWorkingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TideTracker.WeatherStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Lat");

                    b.Property<int>("Long");

                    b.Property<string>("Nickname");

                    b.Property<string>("State");

                    b.Property<int>("StationId");

                    b.HasKey("Id");

                    b.ToTable("WeatherStations");

                    b.HasData(
                        new { Id = 1, Lat = 30, Long = -88, Nickname = "Coast Guard Sector", State = "Alabama", StationId = 8736897 },
                        new { Id = 2, Lat = 30, Long = -88, Nickname = "Dauphin Island", State = "Alabama", StationId = 8735180 },
                        new { Id = 3, Lat = 61, Long = -149, Nickname = "Anchorage", State = "Alaska", StationId = 9455920 },
                        new { Id = 4, Lat = 41, Long = -124, Nickname = "Crescent City", State = "California", StationId = 9419750 },
                        new { Id = 5, Lat = 41, Long = -72, Nickname = "New London", State = "Connecticut", StationId = 8461490 },
                        new { Id = 6, Lat = 39, Long = -75, Nickname = "Delaware City", State = "Delaware", StationId = 8551762 },
                        new { Id = 7, Lat = 30, Long = -87, Nickname = "Pensacola", State = "Florida", StationId = 8729840 },
                        new { Id = 8, Lat = 32, Long = -80, Nickname = "Fort Pulaski", State = "Georgia", StationId = 8670870 },
                        new { Id = 9, Lat = 19, Long = -155, Nickname = "Hilo Bay", State = "Hawaii", StationId = 1617760 },
                        new { Id = 10, Lat = 41, Long = -87, Nickname = "Calumet Harbor", State = "Illinois", StationId = 9087044 },
                        new { Id = 11, Lat = 29, Long = -92, Nickname = "Freshwater Canal Locks", State = "Louisiana", StationId = 8766072 },
                        new { Id = 12, Lat = 44, Long = -66, Nickname = "Eastport", State = "Maine", StationId = 8410140 },
                        new { Id = 13, Lat = 39, Long = -76, Nickname = "Baltimore, Fort McHenry", State = "Maryland", StationId = 8574680 },
                        new { Id = 14, Lat = 42, Long = -71, Nickname = "Boston", State = "Massachusetts", StationId = 8443970 },
                        new { Id = 15, Lat = 45, Long = -84, Nickname = "Mackinaw City", State = "Michigan", StationId = 9075080 },
                        new { Id = 16, Lat = 46, Long = -92, Nickname = "Duluth", State = "Minnesota", StationId = 9099064 },
                        new { Id = 17, Lat = 47, Long = -90, Nickname = "Grand Marais", State = "Minnesota", StationId = 9099090 },
                        new { Id = 18, Lat = 31, Long = -89, Nickname = "Bay Waveland", State = "Mississippi", StationId = 8747437 },
                        new { Id = 19, Lat = 43, Long = -70, Nickname = "Fort Point", State = "New Hampshire", StationId = 8423898 },
                        new { Id = 20, Lat = 40, Long = -74, Nickname = "Sandy Hook", State = "New Jersey", StationId = 8531680 },
                        new { Id = 21, Lat = 42, Long = -73, Nickname = "Turkey Point Hudson River", State = "New York", StationId = 8518962 },
                        new { Id = 22, Lat = 34, Long = -77, Nickname = "Wilmington", State = "North Carolina", StationId = 8658120 },
                        new { Id = 23, Lat = 41, Long = -82, Nickname = "Marblehead", State = "Ohio", StationId = 9063079 },
                        new { Id = 24, Lat = 42, Long = -124, Nickname = "Port Orford", State = "Oregon", StationId = 9431647 },
                        new { Id = 25, Lat = 39, Long = -75, Nickname = "Marcus Hook", State = "Pennsylvania", StationId = 8540433 },
                        new { Id = 26, Lat = 41, Long = -71, Nickname = "Newport", State = "Rhode Island", StationId = 8452660 },
                        new { Id = 27, Lat = 32, Long = -79, Nickname = "Charleston, Cooper River Entrance", State = "South Carolina", StationId = 8665530 },
                        new { Id = 28, Lat = 29, Long = -94, Nickname = "High Island", State = "Texas", StationId = 8770808 },
                        new { Id = 29, Lat = 36, Long = -76, Nickname = "Money Point", State = "Virginia", StationId = 8639348 },
                        new { Id = 30, Lat = 46, Long = -123, Nickname = "Toke Point", State = "Washington", StationId = 9440910 },
                        new { Id = 31, Lat = 44, Long = -88, Nickname = "Green Bay", State = "Wisconsin", StationId = 9087079 },
                        new { Id = 32, Lat = 67, Long = -164, Nickname = "Red Dog Dock", State = "Alaska", StationId = 9491094 },
                        new { Id = 33, Lat = 60, Long = -145, Nickname = "Cordova", State = "Alaska", StationId = 9454050 },
                        new { Id = 34, Lat = 61, Long = -146, Nickname = "Valdez", State = "Alaska", StationId = 9454240 },
                        new { Id = 35, Lat = 57, Long = -152, Nickname = "Kodiak Island", State = "Alaska", StationId = 9457292 },
                        new { Id = 36, Lat = 56, Long = -154, Nickname = "Alitak", State = "Alaska", StationId = 9457804 },
                        new { Id = 37, Lat = 55, Long = -160, Nickname = "Port Moller", State = "Alaska", StationId = 9463502 },
                        new { Id = 38, Lat = 55, Long = -160, Nickname = "Sand Point", State = "Alaska", StationId = 9459450 },
                        new { Id = 39, Lat = 55, Long = -162, Nickname = "King Cove", State = "Alaska", StationId = 9459881 },
                        new { Id = 40, Lat = 53, Long = -166, Nickname = "Unalaska", State = "Alaska", StationId = 9462620 },
                        new { Id = 41, Lat = 52, Long = -174, Nickname = "Atka", State = "Alaska", StationId = 9461710 },
                        new { Id = 42, Lat = 51, Long = -176, Nickname = "Adak Island", State = "Alaska", StationId = 9461380 },
                        new { Id = 43, Lat = 38, Long = -123, Nickname = "Arena Cove", State = "California", StationId = 9416841 },
                        new { Id = 44, Lat = 37, Long = -122, Nickname = "Point Reyes", State = "California", StationId = 9415020 },
                        new { Id = 45, Lat = 38, Long = -122, Nickname = "Port Chicago", State = "California", StationId = 9415144 },
                        new { Id = 46, Lat = 38, Long = -122, Nickname = "Martinez-Amorco Pier", State = "California", StationId = 9415102 },
                        new { Id = 47, Lat = 37, Long = -122, Nickname = "San Francisco", State = "California", StationId = 9414290 },
                        new { Id = 48, Lat = 37, Long = -122, Nickname = "Alameda", State = "California", StationId = 9414750 },
                        new { Id = 49, Lat = 37, Long = -122, Nickname = "Redwood City", State = "California", StationId = 9414523 },
                        new { Id = 50, Lat = 35, Long = -120, Nickname = "Port San Luis", State = "California", StationId = 9412110 },
                        new { Id = 51, Lat = 34, Long = -118, Nickname = "Santa Monica", State = "California", StationId = 9410840 },
                        new { Id = 52, Lat = 32, Long = -117, Nickname = "La Jolla", State = "California", StationId = 9410230 },
                        new { Id = 53, Lat = 41, Long = -72, Nickname = "New Haven", State = "Connecticut", StationId = 8465705 },
                        new { Id = 54, Lat = 41, Long = -73, Nickname = "Bridgeport", State = "Connecticut", StationId = 8467150 },
                        new { Id = 55, Lat = 38, Long = -75, Nickname = "Brandywine Shoal Light", State = "Delaware", StationId = 8555889 },
                        new { Id = 56, Lat = 38, Long = -75, Nickname = "Lewes", State = "Delaware", StationId = 8557380 },
                        new { Id = 57, Lat = 30, Long = -85, Nickname = "Panama City Beach", State = "Florida", StationId = 8729210 },
                        new { Id = 58, Lat = 30, Long = -85, Nickname = "Panama City", State = "Florida", StationId = 8729108 },
                        new { Id = 59, Lat = 29, Long = -84, Nickname = "Apalachicola", State = "Florida", StationId = 8728690 },
                        new { Id = 60, Lat = 30, Long = -81, Nickname = "Fernandina Beach", State = "Florida", StationId = 8720030 },
                        new { Id = 61, Lat = 30, Long = -81, Nickname = "Mayport, Bar Pilots Dock", State = "Florida", StationId = 8720218 },
                        new { Id = 62, Lat = 29, Long = -83, Nickname = "Cedar Key", State = "Florida", StationId = 8727520 },
                        new { Id = 63, Lat = 28, Long = -80, Nickname = "Trident Pier, Port Canaveral", State = "Florida", StationId = 8721604 },
                        new { Id = 64, Lat = 27, Long = -82, Nickname = "Clearwater Beach", State = "Florida", StationId = 8726724 },
                        new { Id = 65, Lat = 27, Long = -82, Nickname = "Old Port Tampa", State = "Florida", StationId = 8726607 },
                        new { Id = 66, Lat = 27, Long = -82, Nickname = "St. Petersburg, Tampa Bay", State = "Florida", StationId = 8726520 },
                        new { Id = 67, Lat = 26, Long = -81, Nickname = "Fort Myers, Caloosahatchee River", State = "Florida", StationId = 8725520 },
                        new { Id = 68, Lat = 26, Long = -80, Nickname = "Lake Worth Pier, Atlantic Ocean", State = "Florida", StationId = 8722670 },
                        new { Id = 69, Lat = 25, Long = -80, Nickname = "Virginia Key, Biscayne Bay", State = "Florida", StationId = 8723214 },
                        new { Id = 70, Lat = 24, Long = -81, Nickname = "Vaca Key, Florida Bay", State = "Florida", StationId = 8723970 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
