// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server;

namespace server.Migrations
{
    [DbContext(typeof(TideTrackerContext))]
    [Migration("20181003193310_dataDisplaying")]
    partial class dataDisplaying
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TideTracker.WeatherStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Lat");

                    b.Property<int>("Long");

                    b.Property<string>("Nickname");

                    b.Property<string>("State");

                    b.Property<int>("StationId");

                    b.HasKey("Id");

                    b.ToTable("WeatherStations");

                    b.HasData(
                        new { Id = 1, Lat = 31, Long = -88, Nickname = "Mobile State Docks", State = "Alabama", StationId = 8737048 },
                        new { Id = 2, Lat = 30, Long = -87, Nickname = "Weeks Bay", State = "Alabama", StationId = 8732828 },
                        new { Id = 3, Lat = 30, Long = -88, Nickname = "Dauphin Island", State = "Alabama", StationId = 8735180 },
                        new { Id = 4, Lat = 61, Long = -149, Nickname = "Anchorage", State = "Alaska", StationId = 9455920 },
                        new { Id = 5, Lat = 41, Long = -124, Nickname = "Crescent City", State = "California", StationId = 9419750 },
                        new { Id = 6, Lat = 41, Long = -72, Nickname = "New London", State = "Connecticut", StationId = 8461490 },
                        new { Id = 7, Lat = 39, Long = -75, Nickname = "Delaware City", State = "Delaware", StationId = 8551762 },
                        new { Id = 8, Lat = 27, Long = -82, Nickname = "McKay Bay", State = "Florida", StationId = 8726667 },
                        new { Id = 9, Lat = 32, Long = -80, Nickname = "Fort Pulaski", State = "Georgia", StationId = 8670870 },
                        new { Id = 10, Lat = 19, Long = -155, Nickname = "Hilo Bay", State = "Hawaii", StationId = 1617760 },
                        new { Id = 11, Lat = 41, Long = -87, Nickname = "Calumet Harbor", State = "Illinois", StationId = 9087044 },
                        new { Id = 12, Lat = 29, Long = -92, Nickname = "Freshwater Canal Locks", State = "Louisiana", StationId = 8766072 },
                        new { Id = 13, Lat = 44, Long = -66, Nickname = "Eastport", State = "Maine", StationId = 8410140 },
                        new { Id = 14, Lat = 39, Long = -76, Nickname = "Baltimore, Fort McHenry", State = "Maryland", StationId = 8574680 },
                        new { Id = 15, Lat = 42, Long = -71, Nickname = "Boston", State = "Massachusetts", StationId = 8443970 },
                        new { Id = 16, Lat = 45, Long = -84, Nickname = "Mackinaw City", State = "Michigan", StationId = 9075080 },
                        new { Id = 17, Lat = 46, Long = -92, Nickname = "Duluth", State = "Minnesota", StationId = 9099064 },
                        new { Id = 18, Lat = 47, Long = -90, Nickname = "Grand Marais", State = "Minnesota", StationId = 9099090 },
                        new { Id = 19, Lat = 31, Long = -89, Nickname = "Bay Waveland", State = "Mississippi", StationId = 8747437 },
                        new { Id = 20, Lat = 43, Long = -70, Nickname = "Fort Point", State = "New Hampshire", StationId = 8423898 },
                        new { Id = 21, Lat = 40, Long = -74, Nickname = "Sandy Hook", State = "New Jersey", StationId = 8531680 },
                        new { Id = 22, Lat = 42, Long = -73, Nickname = "Turkey Point Hudson River", State = "New York", StationId = 8518962 },
                        new { Id = 23, Lat = 34, Long = -77, Nickname = "Wilmington", State = "North Carolina", StationId = 8658120 },
                        new { Id = 24, Lat = 41, Long = -82, Nickname = "Marblehead", State = "Ohio", StationId = 9063079 },
                        new { Id = 25, Lat = 42, Long = -124, Nickname = "Port Orford", State = "Oregon", StationId = 9431647 },
                        new { Id = 26, Lat = 39, Long = -75, Nickname = "Marcus Hook", State = "Pennsylvania", StationId = 8540433 },
                        new { Id = 27, Lat = 41, Long = -71, Nickname = "Newport", State = "Rhode Island", StationId = 8452660 },
                        new { Id = 28, Lat = 32, Long = -79, Nickname = "Charleston, Cooper River Entrance", State = "South Carolina", StationId = 8665530 },
                        new { Id = 29, Lat = 29, Long = -94, Nickname = "High Island", State = "Texas", StationId = 8770808 },
                        new { Id = 30, Lat = 36, Long = -76, Nickname = "Money Point", State = "Virginia", StationId = 8639348 },
                        new { Id = 31, Lat = 46, Long = -123, Nickname = "Toke Point", State = "Washington", StationId = 9440910 },
                        new { Id = 32, Lat = 44, Long = -88, Nickname = "Green Bay", State = "Wisconsin", StationId = 9087079 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
